name: Release to S3

on:
  push:
    branches:
      - master
env:
  ROOT_ACCOUNT: "765419416634"

permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 'pypy-3.8'
    
    - name: determine if push to S3 is required
      id: getdiff
      run: |    
        git diff --name-only HEAD^ HEAD
        if git diff --name-only HEAD^ HEAD | grep -v "^\." | grep "/" | cut -f1 -d"/"| uniq | grep input ; then
          echo "::set-output name=result::true"
    
    - name: Install dependencies
      if: steps.getdiff.outputs.result == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: configure aws credentials
      if: steps.getdiff.outputs.result == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.ROOT_ACCOUNT }}:role/ControlTowerCustomizationPipelineUploadS3
        role-session-name: ControlTowerCustomizationPipelineUploadS3
        aws-region: us-east-1

    - name: Build
      if: steps.getdiff.outputs.result == 'true'
      id: build
      run: |
        if aws_control_tower_manifest_builder \
                --default-region us-east-1 \
                --input-cf input-cf-templates \
                --input-scp input-scps \
                --abort-if-error TRUE \
                --output . ; then 
          echo "::set-output name=result::true"
        else
          echo "::set-output name=result::false"
          exit 1
        fi

    - name: Publish to s3
      if: steps.build.outputs.result == 'true' && steps.getdiff.outputs.result == 'true'
      run: |
        zip -r custom-control-tower-configuration.zip manifest.yaml input-cf-templates input-scps
        aws s3 cp custom-control-tower-configuration.zip  s3://custom-control-tower-configuration-"$ROOT_ACCOUNT"-us-east-1/