name: Release to S3

on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 'pypy-3.8'

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::765419416634:role/ControlTowerCustomizationPipelineUploadS3
        role-session-name: ControlTowerCustomizationPipelineUploadS3
        aws-region: us-east-1

    - name: Publish to s3
      run: |
        output="output/manifest.yaml"
        cf-templates-"input-cf-templates"
        scps="input-scps"
        test -f ./$output && aws s3 cp ./$output s3://custom-control-tower-configuration-765419416634-us-east-1/
        test -d ./$cf-templates && aws s3 cp ./$cf-templates/. s3://custom-control-tower-configuration-765419416634-us-east-1/input-cf-templates/ --recursive
        test -d ./$scps && aws s3 cp ./$scps/. s3://custom-control-tower-configuration-765419416634-us-east-1/input-scps/ --recursive